In [ ]:
import numpy as np
print(np.__version__)

'2.2.2'

In [6]:
a = [10.5,20.3,30.4,40.6,50.7]
print(a)
type(a)
b = np.array(a)
print(b)
print(b+100)

[10.5, 20.3, 30.4, 40.6, 50.7]
[10.5 20.3 30.4 40.6 50.7]
[110.5 120.3 130.4 140.6 150.7]


In [7]:
b.shape
b.dtype

dtype('float64')

In [13]:
a = np.array([1,2,3,4,5,6,7,8,9,10],dtype=complex)
print(a)
a.shape
a.dtype

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]


dtype('complex128')

In [22]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.shape = (3,2)
a.shape
print(a)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
